//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacoes
    {
        public int cdNotificacao { get; set; }
        public string dsNotificacao { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<int> cdUsuario { get; set; }
        public Nullable<System.DateTime> dtLeitura { get; set; }
    }
}
