//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbNotificacoesUsuario
    {
        public int cdNotificacaoUsuario { get; set; }
        public Nullable<int> cdNotificacao { get; set; }
        public Nullable<int> cdUsuario { get; set; }
        public Nullable<System.DateTime> dtLeitura { get; set; }
        public Nullable<int> cdStatus { get; set; }
        public Nullable<bool> stOcultarNotificacao { get; set; }
        public string dsURL { get; set; }
    
        public virtual TbNotificaco TbNotificaco { get; set; }
    }
}
