//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbNotificaco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbNotificaco()
        {
            this.TbNotificacoesUsuarios = new HashSet<TbNotificacoesUsuario>();
        }
    
        public int cdNotificacao { get; set; }
        public string dsNotificacao { get; set; }
        public Nullable<int> cdUsuarioCriacaoNotificacao { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<int> cdStatus { get; set; }
        public string dsIcone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbNotificacoesUsuario> TbNotificacoesUsuarios { get; set; }
    }
}
